### ISSUE TITLE
Can't render headers after they are sent to the client

### ISSUE THREAD

**Issue by mschipperheyn** [snlangsuan/facebook-bot-messenger#3]
It seems there is an error in botmessenger.js line 161. 
After writeHead, the headers are baked in and you can only call res.write(data), and finally res.end(data).

Since you don't include a return after line 159, the writeHead function is called again after the response is completed, leading to the `Can't render headers after they are sent to the client` error.

**Comment by snlangsuan** [comment]
thank you.
